# Generated by Django 4.2.6 on 2023-10-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('property_title', models.CharField(max_length=200)),
                ('property_description', models.TextField()),
                ('property_type', models.CharField(max_length=50)),
                ('property_category', models.CharField(choices=[('luxury', 'Luxury Estate'), ('oceanfront', 'Oceanfront Retreats'), ('urban', 'Urban Living Gems'), ('countryside', 'Countryside Escapes')], default='luxury', max_length=20)),
                ('property_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_location', models.CharField(max_length=100)),
                ('property_features', models.TextField(blank=True, null=True)),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_email', models.EmailField(max_length=254)),
                ('seller_phone', models.CharField(max_length=15)),
                ('property_images', models.ImageField(blank=True, null=True, upload_to='property_images/')),
            ],
        ),
    ]
